# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - gotip version
      - task --version
  init:
    cmds:
      - gotip mod init app
      - touch main.go
  fmt:
    cmds:
      - gotip fmt .
  vet:
    cmds:
      - gotip vet .
  run:
    deps: [ fmt, vet ]
    cmds:
      - gotip run .
  doc:
    cmds:
      - gotip doc {{.CLI_ARGS}}
  version:
    cmds:
      - gotip version
  clean:
    cmds:
      - rm -f ./*.go
      - rm -f ./*.mod
      - rm -f ./*.sum
